sonar 2

diff --git a/.github/workflows/gradle-master.yml b/.github/workflows/gradle-master.yml
--- a/.github/workflows/gradle-master.yml
+++ b/.github/workflows/gradle-master.yml
@@ -19,50 +19,51 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        java-version: '17'
-        distribution: 'temurin'
+      - uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-    - name: Grand executive permission for gradlew
-      run: chmod +x ./gradlew
+      - name: Grand executive permission for gradlew
+        run: chmod +x ./gradlew
 
-    - name: Gradlew clean
-      run: ./gradlew clean
+      - name: Gradlew clean
+        run: ./gradlew clean
 
-    - name: Gradlew test run
-      id: test
-      run: ./gradlew test
+      - name: Gradlew test run
+        id: test
+        run: ./gradlew test
 
-    - name: Analyze with SonarCloud
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      run: ./gradlew sonar
+      - name: Sonar scan
+        uses: jinguji/sonarcloud-gradle-github-action@v2
+        with:
+          sonar-token: ${{ secrets.SONAR_TOKEN }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Successful tests
-      if: steps.test.outcome != 'success'
-      run: |
-        echo "Tests error"
-        exit 1
+      - name: Successful tests
+        if: steps.test.outcome != 'success'
+        run: |
+          echo "Tests error"
+          exit 1
 
-    - name: Successful build
-      uses: appleboy/telegram-action@master
-      with:
-        to: ${{ secrets.TELEGRAM_ME }}
-        token: ${{ secrets.TELEGRAM_NOT }}
-        message: |
-          ✅ Application build done
-          Check report on https://github.com/Winnie-the-Pooh2019/home/actions
+      - name: Successful build
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_ME }}
+          token: ${{ secrets.TELEGRAM_NOT }}
+          message: |
+            ✅ Application build done
+            Check report on https://github.com/Winnie-the-Pooh2019/home/actions
 
-    - name: Send alert in Telegram
-      if: failure()
-      uses: appleboy/telegram-action@master
-      with:
-        to: ${{ secrets.TELEGRAM_ME }}
-        token: ${{ secrets.TELEGRAM_NOT }}
-        message: |
-          ❌ Failed to build
-          Check report on https://github.com/Winnie-the-Pooh2019/home/actions
+      - name: Send alert in Telegram
+        if: failure()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_ME }}
+          token: ${{ secrets.TELEGRAM_NOT }}
+          message: |
+            ❌ Failed to build
+            Check report on https://github.com/Winnie-the-Pooh2019/home/actions
